Repository approvers/radwimpiece, pull requests merged in 2023-05, with the labels that each got.

#2 docs: `CONTRIBUTING.md` の作成
  CONTRIBUTING.md
Labels: documentation

#5 docs: 設計概要
  docs/ARCHITECTURE.md
  docs/schema.ts
Labels: documentation, enhancement

#4 feat: 環境構築
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  index.html
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  rome.json
  src/index.test.ts
  src/index.tsx
  tailwind.config.cjs
  tsconfig.json
  vite.config.ts
Labels: enhancement

#9 chore(deps): 依存に `zod` を追加
  docs/schema.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#8 feat: ゲーム管理するコンポーネントの追加
  src/components/Game.tsx
  src/index.tsx
Labels: enhancement
